spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_author
    username: root
    password: Trankhacnhu132!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect